name: pytest_ps1

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: pyenv-win pytest_ps1 (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, windows-11-arm]
    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: pytest_ps1 pwsh command
        shell: pwsh
        env:
          SRC_REPO: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
          SRC_REF: ${{ github.event.pull_request.head.sha || github.sha }}
        run: |
          Write-Host "Installing from $env:SRC_REPO @ $env:SRC_REF"
          ./pyenv-win/install-pyenv-win.ps1 -Repo $env:SRC_REPO -Ref $env:SRC_REF

      - name: pytest bash script
        run: bash ./.github/scripts/ps1.sh
        shell: bash
